{{- if .Values.gitrepository }}
{{- range .Values.gitrepository }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  {{- toYaml .metadata | nindent 2 }}
  {{- toYaml $.Values.metadata | nindent 2 }}
spec:
  {{- tpl (toYaml .spec) $ | nindent 2 }}
---
{{- end }}
{{- end }}
