{{- if and .Values.kustomization .Values.addons }}
{{- range $addon := .Values.addons }}
{{- range $.Values.kustomization }}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ .metadata.name }}-{{ $addon }}
  namespace: {{ .metadata.namespace }}
  {{- toYaml $.Values.metadata | nindent 2 }}
spec:
  commonMetadata:
    {{- toYaml $.Values.metadata | nindent 4 }}
  {{- range $key, $value := .spec -}}
    {{- if eq $key "path" }}
  {{ $key }}: {{ tpl $value $ }}/{{ $addon }}
    {{- else }}
    {{- if typeIs "string" $value }}
  {{ $key }}: {{ $value | nindent 2 | trim }}
    {{- else }}
  {{ $key }}: {{ tpl (toYaml $value) $ | nindent 4 }}
    {{- end }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
